version: '3.1'
services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=portalhuan2009
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress2009
    volumes:
      - mysqldb:/var/lib/mysql
    ports:
      - 3306:3306
  wordpress:
    image: wordpress
    restart: always
    links:
      - mysql
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress2009
    ports:
      - 80:80
    working_dir: /var/www/html
    volumes:
      - wordpress:/var/www/html
volumes:
  wordpress: /hwdata/wordpress
  mysqldb: /hwdata/mysql 